name: Create Index

on: workflow_dispatch
      
jobs:
  createIndex:
  
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
    
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: Create index
        run: deno task index
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: create index
          title: Create index
          body: Create FuseJS index
          branch: index
