name: Test

on: workflow_dispatch
      
jobs:
  test:
  
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
    
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: Run server
        run: deno run --allow-net src/mod.ts
